---
abstract: 'This module generates a set of random points in a 2D plane according to a user-specified probability distribution that is supplied to the module as a 2D histogram in a CSV file'
author:
  - 'Avinash Kak (kak@purdue.edu)'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Algorithm-RandomPointGenerator
no_index:
  directory:
    - t
    - inc
requires:
  File::Basename: 2.84
  Graphics::GnuplotIF: 1.6
  List::Util: 1.39
  Math::Big: 1.12
  Math::Random: 0.71
version: 1.0
